### PR TITLE
LINKTA-140 implement prelaunch sign up form

### PR DESCRIPTION
**Pull request by ejwoods**
## Description

- set up Mantine component library for project
  - wrapped app body in `<MantineProvider>` in `RootLayout` 
  - added `<ColorSchemeScript>` component to `RootLayout`. This is [necessary](https://mantine.dev/theming/color-schemes/#colorschemescript) to ensure no flash of unstyled content (FOUC) or other undesired styling issues when using server rendered components. Switching to Mantine's Headless Provider, as we have previously discussed, would likely fix this issue as well (but come with its own risks). 
  - made `PrelaunchSignUpForm` component a client component with `use client` so it can use Mantine components
  - added tree shaking for Mantine to next config - reduces packages needed for compilation ✨by as much as 70%✨ 
- created `<PrelaunchSignUpForm>` content using Mantine's `useForm` hook, `TextInput`, `Button`, `Box` elements from Mantine, and semantic HTML according to figma mockups
  - `useForm` hook provides:
    - initial state for Name and Email fields
    - validation for Email field
    - necessary functions for `TextInput` and `Button` to manage state via `getInputProps`. [getInputProps Mantine docs link](https://mantine.dev/form/get-input-props/)
  - Note: I had some basic styling on some of these components during development but have removed it all for PR since styling is a separate ticket. See individual commit messages for details. 
  - Note: I have not implemented Optional "Interests" and "How did you hear about us" fields from mockup. We discussed keeping the form very basic, "Name" and "Email" to start. I can add these fields if requested. 
  - Note: I rendered placeholders for the Google and Github sign in buttons as Mantine `Button` components. I'm not strictly sure this is how those buttons will be rendered in the end. 

## Type of change

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📝 Documentation update
- [ ] Other 🗒️ **\*\***\_\_**\*\***

## How Has This Been Tested?

- [x] Manual testing with npm run dev

## Checklist:

- [x] I have performed a self-review of my own code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [x] I have reviewed the [**Security Best Practices Document**](SECURITY_BEST_PRACTICES.md).
- [x] I have followed the [**Naming Conventions Guide**](NAMING_CONVENTIONS_GUIDE.md) for my changes.
- [x] I have ensured that my pull request title is descriptive.

### CODE REVIEW

**Review by kinskiwu — COMMENTED** [review]
Great work on the PrelaunchSignUpForm! Here are a few points for refinement:

- Pls update the form to accept a handleFormSubmit prop from the PreLaunchSignupFlowContainer. This ensures we're correctly managing form submissions from the parent component.
- Pls coordinate with @zhiyi15 to integrate Firebase according to her setup. Implement the signup logic directly within handleFormSubmit, ensuring setFlowState('confirmed') is called post-successful submission. Please replace the placeholder setTimeout with the actual signup logic. 
- For the initial setup, including just name and email fields suffices. Pls confirm with G if Google Sign-In is the only function we need if yes we can remove the Github one.
- We'll focus on styling once all functional aspects are addressed.
- Error handling will be tackled in a separate task to ensure robust error management.

**Comment by kinskiwu** [comment]
I resolved the merge conflict. Just fyi.

**Review by kinskiwu — APPROVED** [review]
Looks good!

**Review by lomeintheory — APPROVED** [review]
Looks great! Tested this branch on my machine and everything checks out.

**Pull request merged**
